import type { CuratedRule } from './types';

/**
 * Original beginner explanations. These are not the Comprehensive Rules.
 * Official wording stays on https://magic.wizards.com/en/rules.
 */
function rule(
  id: string,
  title: string,
  labelFr: string,
  category: string,
  officialRuleNumber: string,
  keywords: readonly string[],
  explanation: readonly [string, string],
  example: readonly [string, string],
  related: readonly string[],
  extra?: {
    citations?: readonly string[];
    interactionOf?: readonly string[];
  },
): CuratedRule {
  return {
    id,
    title,
    labelFr,
    category,
    officialRuleNumber,
    citations: extra?.citations ?? [officialRuleNumber],
    keywords,
    explanation: { en: explanation[0], fr: explanation[1] },
    example: { en: example[0], fr: example[1] },
    related,
    interactionOf: extra?.interactionOf,
  };
}

export const CURATED_RULES: readonly CuratedRule[] = [
  rule(
    'flying',
    'Flying',
    'Vol',
    'keyword',
    '702.9',
    ['flying', 'fly', 'vol'],
    [
      'A creature with flying can be blocked only by creatures that have flying or reach. It can still be affected by spells and abilities that do not need to block it.',
      'Une créature avec le vol ne peut être bloquée que par une créature avec le vol ou la portée. Elle peut quand même être affectée par un sort ou une capacité qui n’a pas besoin de la bloquer.',
    ],
    [
      'A 2/2 with flying attacks. A 5/5 without flying or reach cannot block it. A 1/3 with reach can.',
      'Un 2/2 avec le vol attaque. Un 5/5 sans vol ni portée ne peut pas le bloquer. Un 1/3 avec la portée le peut.',
    ],
    ['reach', 'declare-blockers'],
  ),
  rule(
    'reach',
    'Reach',
    'Portée',
    'keyword',
    '702.17',
    ['reach', 'portee'],
    [
      'Reach lets a creature block an attacker that has flying. Reach does not make the creature fly, and it does not stop ordinary nonflying creatures from blocking it.',
      'La portée permet de bloquer un attaquant qui a le vol. Elle ne fait pas voler la créature, et les créatures sans vol peuvent toujours la bloquer.',
    ],
    [
      'A Spider with reach can block a flying Dragon. A later ground attacker can still be blocked by that Spider.',
      'Une araignée avec la portée peut bloquer un dragon avec le vol. Un attaquant sans vol peut aussi être bloqué par cette araignée.',
    ],
    ['flying', 'declare-blockers'],
  ),
  rule(
    'vigilance',
    'Vigilance',
    'Vigilance',
    'keyword',
    '702.20',
    ['vigilance'],
    [
      'A creature with vigilance does not tap when it attacks. It can still block later in the turn if another combat happens, and it can use tap abilities after attacking.',
      'Une créature avec la vigilance ne s’engage pas quand elle attaque. Elle peut encore bloquer plus tard dans le tour si un autre combat a lieu, et utiliser une capacité avec le symbole d’engagement après avoir attaqué.',
    ],
    [
      'A creature with vigilance attacks and stays untapped, so it is still available to block in an extra combat.',
      'Une créature avec la vigilance attaque et reste dégagée. Elle peut donc bloquer pendant un combat supplémentaire.',
    ],
    ['haste', 'declare-attackers'],
  ),
  rule(
    'haste',
    'Haste',
    'Célérité',
    'keyword',
    '702.10',
    ['haste', 'celerite'],
    [
      'Haste lets a creature attack, and activate abilities with the tap or untap symbol, on the turn it entered the battlefield. Without haste, that creature has summoning sickness for that turn (rule 302.6). Haste does not let it ignore other restrictions.',
      'La célérité permet à une créature d’attaquer, et d’activer une capacité avec le symbole d’engagement ou de dégagement, le tour où elle arrive sur le champ de bataille. Sans célérité, le mal d’invocation l’en empêche pour ce tour (règle 302.6). La célérité n’enlève pas les autres restrictions.',
    ],
    [
      'A creature cast on your turn cannot attack that turn unless it has haste. On later turns it can attack even without haste.',
      'Une créature lancée à votre tour ne peut pas attaquer ce tour-là sans la célérité. Aux tours suivants, elle peut attaquer même sans célérité.',
    ],
    ['vigilance', 'declare-attackers'],
  ),
  rule(
    'first-strike',
    'First strike',
    'Initiative',
    'keyword',
    '702.7',
    ['first strike', 'firststrike'],
    [
      'First strike creates an extra combat-damage step before regular damage. Creatures with first strike or double strike deal damage in that first step. Creatures with only first strike do not deal damage again in the second step.',
      'L’initiative crée une étape de blessures de combat supplémentaire avant les blessures normales. Les créatures avec l’initiative ou la double initiative infligent leurs blessures à cette première étape. Une créature qui n’a que l’initiative n’inflige pas de blessures à la seconde étape.',
    ],
    [
      'A 2/2 with first strike fights a 2/2 without it. The first striker deals damage first. If that is enough to destroy the other creature, the other creature deals no damage back.',
      'Un 2/2 avec l’initiative combat un 2/2 sans initiative. Le premier inflige ses blessures d’abord. Si cela détruit l’autre créature, elle ne renvoie pas de blessures.',
    ],
    ['double-strike', 'combat-damage'],
  ),
  rule(
    'double-strike',
    'Double strike',
    'Double initiative',
    'keyword',
    '702.4',
    ['double strike', 'doublestrike', 'double initiative', 'doubleinitiative', 'dubble strike'],
    [
      'Double strike means the creature deals combat damage in both damage steps: the first-strike step and the regular step. If either step removes the opposing creature first, that creature may not get to strike back.',
      'La double initiative signifie que la créature inflige des blessures de combat aux deux étapes : l’étape d’initiative et l’étape normale. Si l’une de ces étapes retire la créature adverse, celle-ci peut ne pas frapper en retour.',
    ],
    [
      'A 3/3 with double strike attacks and is blocked by a 3/3. It deals 3 damage in the first step, which destroys the blocker, then it does not have a blocker left for the second step.',
      'Un 3/3 avec la double initiative attaque et est bloqué par un 3/3. Il inflige 3 blessures à la première étape, ce qui détruit le bloqueur. Il ne reste alors plus de bloqueur pour la seconde étape.',
    ],
    ['first-strike', 'combat-damage'],
  ),
  rule(
    'trample',
    'Trample',
    'Piétinement',
    'keyword',
    '702.19',
    ['trample', 'pietinement'],
    [
      'Trample lets an attacking creature assign combat damage beyond what is needed to destroy its blockers to the player, planeswalker, or battle it is attacking. It still has to assign lethal damage to each blocker, in the blocking order, before any damage tramples over.',
      'Le piétinement permet à un attaquant d’assigner les blessures de combat au-delà de ce qu’il faut pour détruire ses bloqueurs au joueur, au planeswalker ou à la bataille qu’il attaque. Il doit d’abord assigner des blessures létales à chaque bloqueur, dans l’ordre de blocage, avant de faire passer le surplus.',
    ],
    [
      'A 5/5 with trample is blocked by a 2/2. It can assign 2 damage to the blocker and 3 to the defending player.',
      'Un 5/5 avec le piétinement est bloqué par un 2/2. Il peut assigner 2 blessures au bloqueur et 3 au joueur défenseur.',
    ],
    ['deathtouch', 'damage-assignment', 'deathtouch-trample'],
  ),
  rule(
    'deathtouch',
    'Deathtouch',
    'Contact mortel',
    'keyword',
    '702.2',
    ['deathtouch', 'contact mortel', 'death touch'],
    [
      'Any amount of damage a deathtouch source deals to a creature is lethal. In combat, 1 damage from that creature is enough to count as lethal damage when assigning damage. The creature is destroyed the next time state-based actions are checked, even if the damage was less than its toughness.',
      'N’importe quelle quantité de blessures infligée à une créature par une source avec le contact mortel est létale. Au combat, 1 blessure de cette créature suffit comme blessure létale au moment de l’assignation. La créature est détruite à la prochaine vérification des actions basées sur l’état, même si les blessures sont inférieures à son endurance.',
    ],
    [
      'A 1/1 with deathtouch blocks a 6/6. The 1 damage is enough to destroy the 6/6 when state-based actions are checked.',
      'Un 1/1 avec le contact mortel bloque un 6/6. Cette unique blessure suffit à détruire le 6/6 lors de la vérification des actions basées sur l’état.',
    ],
    ['trample', 'state-based-actions', 'deathtouch-trample'],
  ),
  rule(
    'deathtouch-trample',
    'Deathtouch and trample',
    'Contact mortel et piétinement',
    'interaction',
    '702.19',
    ['deathtouch and trample', 'deathtouch with trample', 'contact mortel et pietinement'],
    [
      'When one attacking creature has both deathtouch and trample, 1 damage is lethal for each blocker it is assigning damage to. Trample then lets the rest of its combat damage be assigned to the player, planeswalker, or battle it is attacking. Both parts still follow the blocking order. This note only covers that pair of abilities.',
      'Quand un attaquant a à la fois le contact mortel et le piétinement, 1 blessure est létale pour chaque bloqueur auquel il assigne des blessures. Le piétinement permet ensuite d’assigner le reste au joueur, au planeswalker ou à la bataille attaqués. L’ordre de blocage s’applique toujours. Cette note ne couvre que cette paire de capacités.',
    ],
    [
      'A 4/4 with deathtouch and trample is blocked by a 5/5. It can assign 1 damage to the blocker and 3 to the defending player.',
      'Un 4/4 avec le contact mortel et le piétinement est bloqué par un 5/5. Il peut assigner 1 blessure au bloqueur et 3 au joueur défenseur.',
    ],
    ['deathtouch', 'trample', 'damage-assignment'],
    { citations: ['702.2', '702.19'], interactionOf: ['deathtouch', 'trample'] },
  ),
  rule(
    'hexproof',
    'Hexproof',
    'Défense talismanique',
    'keyword',
    '702.11',
    ['hexproof', 'defense talismanique', 'hex proof'],
    [
      'Hexproof means your opponents cannot choose that permanent or player as a target for their spells and abilities. You can still target your own hexproof permanent. Hexproof does nothing against effects that do not use the word target, so a board wipe that destroys all creatures still destroys it. It also does not stop damage from unblocked creatures.',
      'La défense talismanique empêche vos adversaires de choisir ce permanent ou ce joueur comme cible de leurs sorts et capacités. Vous pouvez toujours cibler votre propre permanent avec la défense talismanique. Elle ne protège pas des effets qui n’utilisent pas le mot « cible » : un sort qui détruit toutes les créatures la détruit quand même. Elle n’empêche pas non plus les blessures d’une créature non bloquée.',
    ],
    [
      'An opponent’s “destroy target creature” cannot choose your hexproof creature. An opponent’s “destroy all creatures” can still destroy it, because that spell has no target.',
      'Le « détruisez la créature ciblée » d’un adversaire ne peut pas choisir votre créature avec la défense talismanique. Le « détruisez toutes les créatures » d’un adversaire peut quand même la détruire, car ce sort n’a pas de cible.',
    ],
    ['shroud', 'ward', 'protection'],
  ),
  rule(
    'shroud',
    'Shroud',
    'Linceul',
    'keyword',
    '702.18',
    ['shroud', 'linceul'],
    [
      'Shroud means nobody can target that permanent or player, including its controller. Like hexproof, it only stops targeting. Effects that do not target still work.',
      'Le linceul signifie que personne ne peut cibler ce permanent ou ce joueur, pas même son contrôleur. Comme la défense talismanique, il n’empêche que le ciblage. Les effets qui ne ciblent pas fonctionnent toujours.',
    ],
    [
      'You cannot cast your own “target creature gets +3/+3” on your creature if it has shroud. You can still cast that spell on a different creature you control.',
      'Vous ne pouvez pas lancer votre propre « la créature ciblée gagne +3/+3 » sur votre créature si elle a le linceul. Vous pouvez lancer ce sort sur une autre créature que vous contrôlez.',
    ],
    ['hexproof', 'ward'],
  ),
  rule(
    'ward',
    'Ward',
    'Parade',
    'keyword',
    '702.21',
    ['ward', 'parade'],
    [
      'Ward is a triggered ability. When an opponent’s spell or ability targets the permanent, that opponent may pay the ward cost. If they do not, their spell or ability is countered. Ward does not stop you from targeting your own permanent, and it does not stop effects that never target it.',
      'La parade est une capacité déclenchée. Quand un sort ou une capacité d’un adversaire cible le permanent, cet adversaire peut payer le coût de parade. S’il ne le paie pas, son sort ou sa capacité est contrecarré. La parade ne vous empêche pas de cibler votre propre permanent, et elle n’arrête pas un effet qui ne le cible pas.',
    ],
    [
      'An opponent targets your creature with ward {2}. They can pay {2} and let the spell continue, or decline and the spell is countered. A spell that does not target the creature never asks them to pay.',
      'Un adversaire cible votre créature avec parade {2}. Il peut payer {2} et laisser le sort continuer, ou refuser : le sort est alors contrecarré. Un sort qui ne cible pas la créature ne demande aucun paiement.',
    ],
    ['hexproof', 'shroud'],
  ),
  rule(
    'protection',
    'Protection',
    'Protection',
    'keyword',
    '702.16',
    ['protection'],
    [
      'Protection from a quality stops four things from that quality: damage, enchanting or equipping, blocking, and targeting. It does not stop effects that do not do one of those four. Protection from a color does not stop a board wipe of that color that does not target and does not deal damage.',
      'La protection contre une qualité empêche quatre choses venant de cette qualité : les blessures, enchanter ou s’équiper, bloquer, et cibler. Elle n’empêche pas un effet qui ne fait aucune de ces quatre choses. La protection contre une couleur n’arrête pas un sort de cette couleur qui détruit toutes les créatures sans les cibler et sans infliger de blessures.',
    ],
    [
      'A creature with protection from red cannot be the target of a red burn spell, and red damage that would be dealt to it is prevented. A red spell that destroys all creatures without targeting them can still destroy it.',
      'Une créature avec la protection contre le rouge ne peut pas être la cible d’un sort rouge de blessures, et les blessures rouges qui lui seraient infligées sont prévenues. Un sort rouge qui détruit toutes les créatures sans les cibler peut quand même la détruire.',
    ],
    ['hexproof', 'indestructible', 'shroud'],
  ),
  rule(
    'indestructible',
    'Indestructible',
    'Indestructible',
    'keyword',
    '702.12',
    ['indestructible'],
    [
      'Damage and “destroy” effects do not destroy an indestructible permanent. Lethal damage still marks it, but the destruction state-based action does not remove it. Indestructible does not stop toughness becoming 0 or less, sacrifice, exile, or a player losing the game.',
      'Les blessures et les effets « détruisez » ne détruisent pas un permanent indestructible. Les blessures létales le marquent quand même, mais l’action basée sur l’état qui détruit ne le retire pas. L’indestructible n’empêche pas une endurance de 0 ou moins, le sacrifice, l’exil, ni la défaite d’un joueur.',
    ],
    [
      'A 1/1 indestructible creature can take 5 damage and stay on the battlefield. Giving it -2/-2 until end of turn makes its toughness 0 or less, so it is put into the graveyard anyway.',
      'Une créature 1/1 indestructible peut subir 5 blessures et rester sur le champ de bataille. Lui donner -2/-2 jusqu’à la fin du tour met son endurance à 0 ou moins : elle est mise au cimetière quand même.',
    ],
    ['state-based-actions', 'protection'],
  ),
  rule(
    'lifelink',
    'Lifelink',
    'Lien de vie',
    'keyword',
    '702.15',
    ['lifelink', 'lien de vie', 'life link'],
    [
      'When a source with lifelink deals damage, its controller gains that much life. The life gain happens as part of the damage, not as a separate trigger that can be responded to. It counts combat damage and other damage that source deals.',
      'Quand une source avec le lien de vie inflige des blessures, son contrôleur gagne autant de points de vie. Ce gain fait partie des blessures : ce n’est pas un déclenchement séparé auquel on peut répondre. Cela compte les blessures de combat et les autres blessures de cette source.',
    ],
    [
      'A 3/3 with lifelink deals 3 combat damage to a player. Its controller gains 3 life at the same time.',
      'Un 3/3 avec le lien de vie inflige 3 blessures de combat à un joueur. Son contrôleur gagne 3 points de vie en même temps.',
    ],
    ['combat-damage', 'damage-assignment'],
  ),
  rule(
    'menace',
    'Menace',
    'Menace',
    'keyword',
    '702.111',
    ['menace'],
    [
      'A creature with menace cannot be blocked except by two or more creatures. One blocker is not enough. Menace does not change how much damage it deals once it is blocked.',
      'Une créature avec la menace ne peut pas être bloquée, sauf par deux créatures ou plus. Un seul bloqueur ne suffit pas. La menace ne change pas la quantité de blessures qu’elle inflige une fois bloquée.',
    ],
    [
      'A creature with menace attacks. The defending player has only one untapped creature, so they cannot block it. With two untapped creatures, they can block it.',
      'Une créature avec la menace attaque. Le défenseur n’a qu’une créature dégagée : il ne peut pas la bloquer. Avec deux créatures dégagées, il le peut.',
    ],
    ['declare-blockers', 'flying'],
  ),
  rule(
    'defender',
    'Defender',
    'Défenseur',
    'keyword',
    '702.3',
    ['defender', 'defenseur'],
    [
      'A creature with defender cannot attack. It can still block, and it can still be tapped for other reasons. An effect that says it can attack as though it did not have defender is what lets it attack.',
      'Une créature avec le défenseur ne peut pas attaquer. Elle peut toujours bloquer, et elle peut être engagée pour d’autres raisons. Seul un effet qui dit qu’elle peut attaquer comme si elle n’avait pas le défenseur la laisse attaquer.',
    ],
    [
      'A Wall with defender can block an attacker on an opponent’s turn. On your turn it cannot be declared as an attacker.',
      'Un mur avec le défenseur peut bloquer un attaquant au tour d’un adversaire. À votre tour, il ne peut pas être déclaré attaquant.',
    ],
    ['declare-attackers', 'declare-blockers'],
  ),
  rule(
    'priority',
    'Priority',
    'Priorité',
    'turn',
    '117',
    ['priority', 'priorite'],
    [
      'Priority is permission to cast a spell, activate an ability, or take a special action. After a spell or ability resolves, and at the right points in a step, the active player gets priority first. A player who wants to pass gives priority to the next player. When every player passes in a row, the top object on the stack resolves, or the game moves on if the stack is empty.',
      'La priorité est le droit de lancer un sort, d’activer une capacité ou d’effectuer une action spéciale. Après la résolution d’un sort ou d’une capacité, et aux moments prévus d’une étape, le joueur actif reçoit la priorité en premier. Un joueur qui passe donne la priorité au joueur suivant. Quand tous les joueurs passent d’affilée, l’objet au sommet de la pile se résout, ou la partie avance si la pile est vide.',
    ],
    [
      'You cast a creature spell. You get priority again before your opponent does. If you pass and your opponent also passes, the creature spell resolves.',
      'Vous lancez un sort de créature. Vous recevez à nouveau la priorité avant votre adversaire. Si vous passez et que votre adversaire passe aussi, le sort de créature se résout.',
    ],
    ['stack', 'flash', 'activated-abilities'],
  ),
  rule(
    'stack',
    'Stack',
    'Pile',
    'zone',
    '405',
    ['stack', 'the stack', 'pile'],
    [
      'The stack is the zone where spells and most abilities wait to resolve. The last object put on the stack resolves first. Players can respond while they have priority, which puts a new object on top. Mana abilities and state-based actions do not use the stack.',
      'La pile est la zone où les sorts et la plupart des capacités attendent de se résoudre. Le dernier objet mis sur la pile se résout en premier. Les joueurs peuvent répondre pendant qu’ils ont la priorité, ce qui met un nouvel objet au-dessus. Les capacités de mana et les actions basées sur l’état n’utilisent pas la pile.',
    ],
    [
      'Your opponent casts a spell. You respond with a counterspell. The counterspell is on top, so it resolves first and can counter the spell underneath.',
      'Votre adversaire lance un sort. Vous répondez avec un contresort. Le contresort est au-dessus : il se résout en premier et peut contrecarrer le sort en dessous.',
    ],
    ['priority', 'flash', 'triggered-abilities'],
  ),
  rule(
    'triggered-abilities',
    'Triggered abilities',
    'Capacités déclenchées',
    'ability',
    '603',
    ['triggered ability', 'triggered abilities', 'trigger', 'capacite declenchee', 'capacites declenchees'],
    [
      'A triggered ability starts with “when,” “whenever,” or “at.” It waits for an event. When that event happens, the ability goes on the stack the next time a player would get priority. It can be responded to. It is not optional unless it says “you may.”',
      'Une capacité déclenchée commence par « quand », « à chaque fois que » ou « au ». Elle attend un événement. Quand il arrive, la capacité va sur la pile la prochaine fois qu’un joueur recevrait la priorité. On peut y répondre. Elle n’est pas facultative, sauf si elle dit « vous pouvez ».',
    ],
    [
      '“Whenever a creature enters, draw a card” goes on the stack after the creature enters. An opponent can cast an instant before that draw resolves.',
      '« À chaque fois qu’une créature arrive, piochez une carte » va sur la pile après l’arrivée de la créature. Un adversaire peut lancer un éphémère avant que cette pioche se résolve.',
    ],
    ['stack', 'activated-abilities', 'static-abilities'],
  ),
  rule(
    'activated-abilities',
    'Activated abilities',
    'Capacités activées',
    'ability',
    '602',
    ['activated ability', 'activated abilities', 'activate', 'capacite activee', 'capacites activees'],
    [
      'An activated ability is written as “cost: effect.” You activate it by paying the cost while you have priority, the same way you cast a spell. It goes on the stack and can be responded to. If the cost includes the tap symbol, summoning sickness can stop a creature from activating it.',
      'Une capacité activée s’écrit « coût : effet ». On l’active en payant le coût pendant qu’on a la priorité, comme on lance un sort. Elle va sur la pile et on peut y répondre. Si le coût contient le symbole d’engagement, le mal d’invocation peut empêcher une créature de l’activer.',
    ],
    [
      '“{T}: Draw a card” is an activated ability. You tap the permanent as a cost, then the draw waits on the stack. An opponent can respond before you draw.',
      '« {T} : piochez une carte » est une capacité activée. Vous engagez le permanent comme coût, puis la pioche attend sur la pile. Un adversaire peut répondre avant que vous piochiez.',
    ],
    ['stack', 'priority', 'triggered-abilities', 'haste'],
  ),
  rule(
    'static-abilities',
    'Static abilities',
    'Capacités statiques',
    'ability',
    '604',
    ['static ability', 'static abilities', 'capacite statique', 'capacites statiques'],
    [
      'A static ability is text that is simply true while the permanent or object is in the right zone. It does not go on the stack and nobody can respond to it turning on. Many static abilities create continuous effects. Keywords such as flying and trample are static abilities.',
      'Une capacité statique est un texte qui est simplement vrai tant que le permanent ou l’objet est dans la bonne zone. Elle ne va pas sur la pile, et personne ne peut répondre à son activation. Beaucoup de capacités statiques créent des effets continus. Des mots-clés comme le vol et le piétinement sont des capacités statiques.',
    ],
    [
      '“Creatures you control get +1/+1” applies as soon as the permanent is on the battlefield. There is no trigger to counter.',
      '« Les créatures que vous contrôlez gagnent +1/+1 » s’applique dès que le permanent est sur le champ de bataille. Il n’y a pas de déclenchement à contrecarrer.',
    ],
    ['continuous-effects', 'triggered-abilities', 'activated-abilities'],
  ),
  rule(
    'combat-phase',
    'Combat phase',
    'Phase de combat',
    'combat',
    '506',
    ['combat', 'combat phase', 'combat step', 'phase de combat'],
    [
      'Combat has five steps, in order: beginning of combat, declare attackers, declare blockers, combat damage, and end of combat. If no creatures attack, the declare-blockers and combat-damage steps are skipped. First strike or double strike can add a second combat-damage step.',
      'Le combat a cinq étapes, dans l’ordre : début du combat, déclaration des attaquants, déclaration des bloqueurs, blessures de combat, et fin du combat. Si aucune créature n’attaque, les étapes de déclaration des bloqueurs et de blessures sont passées. L’initiative ou la double initiative peut ajouter une seconde étape de blessures.',
    ],
    [
      'You move to combat, then declare which creatures attack, then your opponent declares blockers, then damage happens, then combat ends. Players get priority in each of those steps.',
      'Vous entrez en combat, vous déclarez les attaquants, votre adversaire déclare les bloqueurs, les blessures ont lieu, puis le combat se termine. Les joueurs reçoivent la priorité à chacune de ces étapes.',
    ],
    ['declare-attackers', 'declare-blockers', 'combat-damage'],
  ),
  rule(
    'declare-attackers',
    'Declare attackers',
    'Déclaration des attaquants',
    'combat',
    '508',
    ['declare attackers', 'attacking', 'declare attackers step', 'declaration des attaquants'],
    [
      'In the declare-attackers step, the active player chooses which creatures they control will attack, and what each one attacks. Tapped creatures, and creatures with summoning sickness or defender, cannot attack. Those attackers tap unless they have vigilance. This declaration does not use the stack.',
      'À l’étape de déclaration des attaquants, le joueur actif choisit quelles créatures qu’il contrôle attaquent, et ce que chacune attaque. Une créature engagée, avec le mal d’invocation ou avec le défenseur, ne peut pas attaquer. Ces attaquants s’engagent, sauf s’ils ont la vigilance. Cette déclaration n’utilise pas la pile.',
    ],
    [
      'You tap two creatures and send both at an opponent. After that declaration, both players can cast instants before blockers are declared.',
      'Vous engagez deux créatures et les envoyez toutes les deux sur un adversaire. Après cette déclaration, les deux joueurs peuvent lancer des éphémères avant la déclaration des bloqueurs.',
    ],
    ['combat-phase', 'haste', 'vigilance', 'defender'],
  ),
  rule(
    'declare-blockers',
    'Declare blockers',
    'Déclaration des bloqueurs',
    'combat',
    '509',
    ['declare blockers', 'blocking', 'block', 'declaration des bloqueurs', 'bloquer', 'bloqueur'],
    [
      'The defending player chooses which untapped creatures they control will block, and which attacking creature each one blocks. A blocker normally blocks only one attacker. Several blockers can block one attacker unless an ability says otherwise. Restrictions such as flying, reach, and menace are checked as blockers are declared. The declaration does not use the stack.',
      'Le joueur défenseur choisit quelles créatures dégagées qu’il contrôle bloquent, et quel attaquant chacune bloque. Un bloqueur ne bloque normalement qu’un seul attaquant. Plusieurs bloqueurs peuvent bloquer un même attaquant, sauf si une capacité dit le contraire. Les restrictions comme le vol, la portée et la menace sont vérifiées au moment de la déclaration. Cette déclaration n’utilise pas la pile.',
    ],
    [
      'One attacker is blocked by two creatures. The attacking player chooses the order of those blockers before damage is assigned.',
      'Un attaquant est bloqué par deux créatures. Le joueur attaquant choisit l’ordre de ces bloqueurs avant d’assigner les blessures.',
    ],
    ['combat-phase', 'flying', 'reach', 'menace', 'damage-assignment'],
  ),
  rule(
    'combat-damage',
    'Combat damage',
    'Blessures de combat',
    'combat',
    '510',
    ['combat damage', 'damage step', 'blessures de combat'],
    [
      'In the combat-damage step, attacking and blocking creatures deal damage equal to their power at the same time, after it has been assigned. First strike and double strike can split this into two steps. Combat damage does not use the stack. Unblocked attackers damage the player, planeswalker, or battle they are attacking.',
      'À l’étape des blessures de combat, les créatures attaquantes et bloqueuses infligent en même temps des blessures égales à leur force, après qu’elles ont été assignées. L’initiative et la double initiative peuvent séparer cela en deux étapes. Les blessures de combat n’utilisent pas la pile. Un attaquant non bloqué blesse le joueur, le planeswalker ou la bataille qu’il attaque.',
    ],
    [
      'A 4/4 attacks and is not blocked. It deals 4 combat damage to the defending player. A 4/4 blocked by a 2/3 deals damage to that blocker instead.',
      'Un 4/4 attaque et n’est pas bloqué. Il inflige 4 blessures de combat au joueur défenseur. Un 4/4 bloqué par un 2/3 inflige ses blessures à ce bloqueur.',
    ],
    ['first-strike', 'double-strike', 'trample', 'lifelink', 'damage-assignment'],
  ),
  rule(
    'damage-assignment',
    'Damage assignment',
    'Attribution des blessures',
    'combat',
    '510.1',
    ['damage assignment', 'assign damage', 'attribution des blessures', 'assigner les blessures'],
    [
      'The attacking player assigns each attacking creature’s combat damage first, then the defending player assigns each blocking creature’s damage. A blocked creature assigns damage to its blockers in the chosen order. It must assign at least lethal damage to a blocker before assigning damage to the next one. Trample is what allows leftover damage to be assigned to the defending player.',
      'Le joueur attaquant assigne d’abord les blessures de combat de chaque attaquant, puis le défenseur assigne les blessures de chaque bloqueur. Une créature bloquée assigne ses blessures à ses bloqueurs dans l’ordre choisi. Elle doit assigner au moins des blessures létales à un bloqueur avant d’en assigner au suivant. Le piétinement est ce qui permet d’assigner le surplus au joueur défenseur.',
    ],
    [
      'A 5/5 blocked by a 1/1 and a 4/4, with the 1/1 ordered first, assigns 1 damage to the 1/1 and 4 to the 4/4. Without trample it cannot assign any of that damage to the player.',
      'Un 5/5 bloqué par un 1/1 puis un 4/4 assigne 1 blessure au 1/1 et 4 au 4/4. Sans piétinement, il ne peut assigner aucune de ces blessures au joueur.',
    ],
    ['trample', 'deathtouch', 'combat-damage', 'deathtouch-trample'],
  ),
  rule(
    'state-based-actions',
    'State-based actions',
    'Actions basées sur l’état',
    'rules',
    '704',
    ['state-based actions', 'state based actions', 'sba', 'actions basees sur l etat', 'actions basees sur letat'],
    [
      'State-based actions are automatic checks the game performs, right before a player would get priority. They do not use the stack and nobody can respond to them one at a time. Familiar checks include a player with 0 or less life, a player with 10 or more poison counters, a creature with toughness 0 or less, a creature with lethal damage, and the legend rule. They repeat until none still apply.',
      'Les actions basées sur l’état sont des vérifications automatiques, juste avant qu’un joueur ne reçoive la priorité. Elles n’utilisent pas la pile, et personne ne peut y répondre une par une. Parmi elles : un joueur à 0 point de vie ou moins, un joueur avec 10 marqueurs « poison » ou plus, une créature d’endurance 0 ou moins, une créature avec des blessures létales, et la règle des légendes. Elles se répètent tant qu’il en reste à appliquer.',
    ],
    [
      'A creature takes damage equal to its toughness. Nobody casts a spell in between. The next time state-based actions are checked, that creature is destroyed.',
      'Une créature subit des blessures égales à son endurance. Personne ne lance de sort entre les deux. À la vérification suivante, cette créature est détruite.',
    ],
    ['poison', 'indestructible', 'priority'],
  ),
  rule(
    'poison',
    'Poison counters',
    'Marqueurs poison',
    'counter',
    '104.3d',
    ['poison', 'poison counter', 'poison counters', 'compteur poison', 'marqueurs poison'],
    [
      'Poison counters sit on a player. A player with ten or more poison counters loses the game the next time state-based actions are checked (rules 104.3d and 704). One poison counter is not a loss. Infect and toxic are separate abilities that can give poison counters. This note does not describe every card that uses them.',
      'Les marqueurs « poison » sont sur un joueur. Un joueur qui en a dix ou plus perd la partie à la prochaine vérification des actions basées sur l’état (règles 104.3d et 704). Un seul marqueur ne fait pas perdre. L’infection et la toxicité sont d’autres capacités qui peuvent donner des marqueurs poison. Cette note ne décrit pas chaque carte qui s’en sert.',
    ],
    [
      'A player goes from 9 poison counters to 10. Before anyone gets priority, state-based actions make that player lose.',
      'Un joueur passe de 9 marqueurs poison à 10. Avant que quelqu’un ne reçoive la priorité, les actions basées sur l’état le font perdre.',
    ],
    ['state-based-actions'],
    { citations: ['104.3d', '122.1f', '704'] },
  ),
  rule(
    'plus-one-counters',
    '+1/+1 counters',
    'Marqueurs +1/+1',
    'counter',
    '122.1',
    ['plusone', 'plusone counter', 'plusone counters', 'plus 1 plus 1', 'marqueurs plusone', 'marqueur plusone'],
    [
      'A +1/+1 counter on a creature raises its power and toughness by 1 for as long as the counter stays there. It is a marker, not a temporary bonus that wears off by itself at end of turn. Rule 122 describes counters. Removing the counter removes the bonus. This is not the same as a -1/-1 counter, which lowers power and toughness instead.',
      'Un marqueur +1/+1 sur une créature augmente sa force et son endurance de 1 tant que le marqueur reste. C’est un marqueur, pas un bonus temporaire qui disparaît seul à la fin du tour. La règle 122 décrit les marqueurs. Retirer le marqueur retire le bonus. Ce n’est pas un marqueur -1/-1, qui diminue la force et l’endurance.',
    ],
    [
      'A 2/2 gets two +1/+1 counters and becomes a 4/4. If one counter is removed, it is a 3/3. A spell that gives +2/+2 until end of turn does not leave a counter behind.',
      'Un 2/2 reçoit deux marqueurs +1/+1 et devient un 4/4. Si un marqueur est retiré, c’est un 3/3. Un sort qui donne +2/+2 jusqu’à la fin du tour ne laisse pas de marqueur.',
    ],
    ['state-based-actions'],
  ),
  rule(
    'flash',
    'Flash',
    'Flash',
    'keyword',
    '702.8',
    ['flash'],
    [
      'Flash lets you cast a spell any time you could cast an instant, including on an opponent’s turn while you have priority. The spell still goes on the stack and can be responded to. Flash does not make the spell uncounterable.',
      'Le flash permet de lancer un sort à tout moment où vous pourriez lancer un éphémère, y compris au tour d’un adversaire pendant que vous avez la priorité. Le sort va quand même sur la pile et on peut y répondre. Le flash ne rend pas le sort incontrable.',
    ],
    [
      'You can cast a creature with flash after an opponent declares attackers, before blockers. It still has summoning sickness if you want to tap it that turn, unless it also has haste.',
      'Vous pouvez lancer une créature avec le flash après qu’un adversaire a déclaré ses attaquants, avant les bloqueurs. Elle a quand même le mal d’invocation si vous voulez l’engager ce tour-là, sauf si elle a aussi la célérité.',
    ],
    ['stack', 'priority', 'haste'],
  ),
  rule(
    'flashback',
    'Flashback',
    'Flashback',
    'keyword',
    '702.34',
    ['flashback', 'flash back'],
    [
      'Flashback lets you cast a card from your graveyard by paying its flashback cost instead of its mana cost. You can do it any time you could cast an instant. If it would leave the stack, it is exiled instead of returning to the graveyard.',
      'Le flashback permet de lancer une carte depuis votre cimetière en payant son coût de flashback à la place de son coût de mana. Vous pouvez le faire à tout moment où vous pourriez lancer un éphémère. Si elle devait quitter la pile, elle est exilée au lieu de retourner au cimetière.',
    ],
    [
      'A sorcery in your graveyard with flashback can be cast on your turn during a main phase, when the stack is empty. After it resolves, it is exiled.',
      'Un rituel dans votre cimetière avec le flashback peut être lancé à votre tour, pendant une phase principale, quand la pile est vide. Après sa résolution, il est exilé.',
    ],
    ['flash', 'stack'],
  ),
  rule(
    'cascade',
    'Cascade',
    'Cascade',
    'keyword',
    '702.85',
    ['cascade'],
    [
      'Cascade triggers when you cast the spell. You exile cards from the top of your library until you exile a nonland card with a lower mana value, then you may cast that card without paying its mana cost. The exiled cards you do not cast go on the bottom of your library in a random order. The cascaded spell is cast as part of resolving the trigger.',
      'La cascade se déclenche quand vous lancez le sort. Vous exilez des cartes du dessus de votre bibliothèque jusqu’à exiler une carte non-terrain de valeur de mana inférieure, puis vous pouvez lancer cette carte sans payer son coût de mana. Les cartes exilées que vous ne lancez pas vont sous votre bibliothèque dans un ordre aléatoire. Le sort cascadé est lancé pendant la résolution de la capacité déclenchée.',
    ],
    [
      'You cast a spell with mana value 4 and cascade. You may cast the first exiled nonland card with mana value 3 or less for free. Your original spell is still on the stack.',
      'Vous lancez un sort de valeur de mana 4 avec la cascade. Vous pouvez lancer gratuitement la première carte non-terrain exilée de valeur de mana 3 ou moins. Votre sort d’origine est toujours sur la pile.',
    ],
    ['triggered-abilities', 'stack'],
  ),
  rule(
    'kicker',
    'Kicker',
    'Kicker',
    'keyword',
    '702.33',
    ['kicker'],
    [
      'Kicker is an optional extra cost you can pay as you cast the spell. If you pay it, the spell is “kicked,” and the card’s extra effect happens. If you do not pay it, you get only the base spell. You decide to kick while casting, not after the spell resolves.',
      'Le kicker est un coût supplémentaire facultatif que vous pouvez payer en lançant le sort. Si vous le payez, le sort est « kické » et l’effet en plus de la carte a lieu. Si vous ne le payez pas, vous n’obtenez que le sort de base. On choisit de kicker pendant le lancement, pas après la résolution.',
    ],
    [
      'A spell costs {2}{R} and has kicker {1}{R}. You may pay {2}{R} for the base spell, or {3}{R}{R} to kick it. You cannot decide to kick it after it is already on the stack.',
      'Un sort coûte {2}{R} et a le kicker {1}{R}. Vous pouvez payer {2}{R} pour le sort de base, ou {3}{R}{R} pour le kicker. Vous ne pouvez pas décider de le kicker une fois qu’il est déjà sur la pile.',
    ],
    ['flash', 'stack'],
  ),
  rule(
    'equip',
    'Equip',
    'Équiper',
    'keyword',
    '702.6',
    ['equip', 'equiper', 'equipment', 'equipement'],
    [
      'Equip is an activated ability of an Equipment. You pay the equip cost and attach that Equipment to a target creature you control. You can activate it only any time you could cast a sorcery. The Equipment stays on the battlefield if the creature leaves. Attaching it to a new creature unattaches it from the old one.',
      'Équiper est une capacité activée d’un équipement. Vous payez le coût d’équipement et attachez cet équipement à une créature ciblée que vous contrôlez. Vous ne pouvez l’activer qu’à un moment où vous pourriez lancer un rituel. L’équipement reste sur le champ de bataille si la créature part. L’attacher à une nouvelle créature le détache de l’ancienne.',
    ],
    [
      'You pay {2} to equip a sword to a creature you control during your main phase, while the stack is empty. You cannot equip it during an opponent’s turn unless another ability says you can.',
      'Vous payez {2} pour équiper une épée à une créature que vous contrôlez pendant votre phase principale, la pile étant vide. Vous ne pouvez pas l’équiper au tour d’un adversaire, sauf si une autre capacité le permet.',
    ],
    ['attach', 'activated-abilities'],
  ),
  rule(
    'attach',
    'Attach',
    'Attacher',
    'action',
    '701.3',
    ['attach', 'attached', 'attacher', 'attache'],
    [
      'To attach an Aura, Equipment, or Fortification is to put it onto another object. An Aura enters attached to the object it targeted, or the object named by the effect that put it onto the battlefield. An Equipment is attached later by equip or another effect. If the object it is attached to leaves the battlefield, the Aura usually goes to the graveyard and the Equipment stays, unattached.',
      'Attacher une aura, un équipement ou une fortification, c’est le mettre sur un autre objet. Une aura arrive attachée à l’objet qu’elle a ciblé, ou à l’objet indiqué par l’effet qui l’a mise sur le champ de bataille. Un équipement est attaché plus tard par équiper ou par un autre effet. Si l’objet auquel il est attaché quitte le champ de bataille, l’aura va en général au cimetière et l’équipement reste, non attaché.',
    ],
    [
      'You cast an Aura that says “enchant creature” and target a creature. As the Aura resolves, it enters attached to that creature. If the creature is destroyed later, the Aura is put into the graveyard.',
      'Vous lancez une aura qui dit « enchanter : créature » et vous ciblez une créature. Quand l’aura se résout, elle arrive attachée à cette créature. Si la créature est détruite plus tard, l’aura est mise au cimetière.',
    ],
    ['equip'],
  ),
  rule(
    'sacrifice',
    'Sacrifice',
    'Sacrifier',
    'action',
    '701.21',
    ['sacrifice', 'sacrifier'],
    [
      'To sacrifice a permanent, its controller puts it into its owner’s graveyard. Only the controller can sacrifice it. Sacrifice is a cost or an effect the card asks for. It does not target the permanent, and indestructible does not stop it. A player cannot sacrifice a permanent they do not control.',
      'Sacrifier un permanent, c’est le mettre dans le cimetière de son propriétaire, par son contrôleur. Seul le contrôleur peut le sacrifier. Le sacrifice est un coût ou un effet demandé par la carte. Il ne cible pas le permanent, et l’indestructible ne l’empêche pas. Un joueur ne peut pas sacrifier un permanent qu’il ne contrôle pas.',
    ],
    [
      'A cost says “sacrifice a creature.” You put a creature you control into your graveyard as you pay. An opponent cannot choose to sacrifice your creature for you.',
      'Un coût dit « sacrifiez une créature ». Vous mettez une créature que vous contrôlez dans votre cimetière en payant. Un adversaire ne peut pas choisir de sacrifier votre créature à votre place.',
    ],
    ['indestructible', 'state-based-actions'],
  ),
  rule(
    'commander',
    'Commander',
    'Commander',
    'commander',
    '903',
    ['commander', 'commandant', 'edh'],
    [
      'Commander is a casual variant in rule 903. Each deck has a commander, a legendary creature, that starts in the command zone. The deck’s cards have to fit that commander’s color identity. The format also adds commander tax and a commander-damage loss. The rest of the variant, including deck size and partners, is in rule 903 rather than in this short note.',
      'Commander est une variante casual décrite à la règle 903. Chaque deck a un commandant, une créature légendaire, qui commence dans la zone de commandement. Les cartes du deck doivent respecter l’identité de couleur de ce commandant. Le format ajoute aussi la taxe de commandant et une défaite par blessures de commandant. Le reste de la variante, y compris la taille du deck et les partenaires, est dans la règle 903, pas dans cette note courte.',
    ],
    [
      'Before the game, each player puts their commander face up in the command zone. The other cards are shuffled into the library.',
      'Avant la partie, chaque joueur met son commandant face visible dans la zone de commandement. Les autres cartes sont mélangées dans la bibliothèque.',
    ],
    ['commander-tax', 'commander-damage', 'color-identity'],
  ),
  rule(
    'commander-tax',
    'Commander tax',
    'Taxe de commandant',
    'commander',
    '903.8',
    ['commander tax', 'command tax', 'taxe de commandant', 'taxe du commandant'],
    [
      'Commander tax is an extra cost to cast your commander from the command zone. For each previous time you cast that commander from the command zone this game, it costs {2} more. The first cast has no tax. The tax is not added when the commander is cast from your hand or another zone, and it is not a counter on the card itself.',
      'La taxe de commandant est un coût supplémentaire pour lancer votre commandant depuis la zone de commandement. Pour chaque fois précédente où vous avez lancé ce commandant depuis la zone de commandement pendant cette partie, il coûte {2} de plus. Le premier lancement n’a pas de taxe. La taxe ne s’ajoute pas s’il est lancé depuis votre main ou une autre zone, et ce n’est pas un marqueur sur la carte.',
    ],
    [
      'The first time you cast your commander from the command zone, you pay its printed cost. The second time, you pay {2} more. The third time, you pay {4} more.',
      'La première fois que vous lancez votre commandant depuis la zone de commandement, vous payez son coût imprimé. La deuxième fois, vous payez {2} de plus. La troisième fois, vous payez {4} de plus.',
    ],
    ['commander', 'commander-damage'],
  ),
  rule(
    'commander-damage',
    'Commander damage',
    'Blessures de commandant',
    'commander',
    '903.10a',
    ['commander damage', 'general damage', 'blessures de commandant', 'degats de commandant'],
    [
      'In a Commander game, a player loses if a single commander has dealt them 21 or more combat damage over the course of the game. It is tracked separately for each commander. Only combat damage counts, not other damage that commander deals. The check is a state-based action (rule 903.10a).',
      'Dans une partie de Commander, un joueur perd si un même commandant lui a infligé 21 blessures de combat ou plus au cours de la partie. On compte séparément pour chaque commandant. Seules les blessures de combat comptent, pas les autres blessures de ce commandant. La vérification est une action basée sur l’état (règle 903.10a).',
    ],
    [
      'One commander deals 10 combat damage to you, then 11 more later in the game. You have 21 combat damage from that commander, so you lose the next time state-based actions are checked. Damage from a different commander is a separate total.',
      'Un commandant vous inflige 10 blessures de combat, puis 11 de plus plus tard. Vous avez 21 blessures de combat de ce commandant, donc vous perdez à la prochaine vérification. Les blessures d’un autre commandant forment un total séparé.',
    ],
    ['commander', 'state-based-actions', 'combat-damage'],
  ),
  rule(
    'color-identity',
    'Color identity',
    'Identité de couleur',
    'commander',
    '903.4',
    ['color identity', 'colour identity', 'identite de couleur'],
    [
      'Color identity is the set of colors used to build a Commander deck. It includes the colors of mana symbols in a card’s mana cost and rules text, plus any color added by a color indicator or a characteristic-defining ability. Reminder text is ignored. A card in the deck can only use colors that are in the commander’s color identity. Lands and other deckbuilding limits are also in rule 903.',
      'L’identité de couleur est l’ensemble des couleurs autorisées dans un deck Commander. Elle comprend les couleurs des symboles de mana dans le coût de mana et le texte de règles de la carte, plus toute couleur ajoutée par un indicateur de couleur ou une capacité définissant une caractéristique. Le texte de rappel est ignoré. Une carte du deck ne peut utiliser que des couleurs présentes dans l’identité du commandant. Les terrains et les autres limites de construction sont aussi dans la règle 903.',
    ],
    [
      'A commander that is only green cannot be paired with a card that has a blue mana symbol in its rules text. A colorless artifact with no colored mana symbols can go in that deck.',
      'Un commandant uniquement vert ne peut pas être accompagné d’une carte qui a un symbole de mana bleu dans son texte de règles. Un artefact incolore sans symbole de mana coloré peut aller dans ce deck.',
    ],
    ['commander'],
  ),
  rule(
    'replacement-effects',
    'Replacement effects',
    'Effets de remplacement',
    'effect',
    '614',
    ['replacement effect', 'replacement effects', 'instead', 'effet de remplacement', 'effets de remplacement'],
    [
      'A replacement effect changes an event as it would happen, often with “if” and “instead.” It does not use the stack, and it is not a triggered ability. The modified event is what actually happens. If several replacement effects want to change the same event, rule 616 tells which player chooses the order. This assistant does not resolve a pile of replacements unless a specific note exists for that pair.',
      'Un effet de remplacement change un événement au moment où il devrait avoir lieu, souvent avec « si » et « à la place ». Il n’utilise pas la pile, et ce n’est pas une capacité déclenchée. C’est l’événement modifié qui a vraiment lieu. Si plusieurs effets de remplacement veulent changer le même événement, la règle 616 indique quel joueur choisit l’ordre. Cet assistant ne tranche pas un empilement d’effets de remplacement, sauf s’il existe une note précise pour cette paire.',
    ],
    [
      'An effect says “if a creature would die, exile it instead.” The creature never hits the graveyard, so “when this dies” abilities do not see a death.',
      'Un effet dit « si une créature devait mourir, exilez-la à la place ». La créature ne va pas au cimetière, donc les capacités « quand ceci meurt » ne voient pas de mort.',
    ],
    ['continuous-effects', 'triggered-abilities'],
  ),
  rule(
    'continuous-effects',
    'Continuous effects',
    'Effets continus',
    'effect',
    '611',
    ['continuous effect', 'continuous effects', 'effet continu', 'effets continus'],
    [
      'A continuous effect changes the game for a duration, such as “creatures you control get +1/+1” or an effect that lasts until end of turn. It is not a one-time instruction and it does not sit on the stack while it applies. Static abilities often create them. When continuous effects disagree, rule 613 applies them in layers. This assistant does not answer a specific layers question unless a curated note covers it.',
      'Un effet continu change la partie pendant une durée, par exemple « les créatures que vous contrôlez gagnent +1/+1 » ou un effet qui dure jusqu’à la fin du tour. Ce n’est pas une instruction ponctuelle, et il ne reste pas sur la pile pendant qu’il s’applique. Les capacités statiques en créent souvent. Quand des effets continus se contredisent, la règle 613 les applique par couches. Cet assistant ne répond pas à une question précise de couches, sauf s’il existe une note pour ce cas.',
    ],
    [
      'An anthem gives your creatures +1/+1 while it is on the battlefield. When the anthem leaves, the bonus ends immediately. No player gets priority in between.',
      'Un hymne donne +1/+1 à vos créatures tant qu’il est sur le champ de bataille. Quand l’hymne part, le bonus cesse immédiatement. Aucun joueur ne reçoit la priorité entre les deux.',
    ],
    ['static-abilities', 'replacement-effects'],
  ),
  rule(
    'the-initiative',
    'The initiative',
    'L’initiative',
    'keyword',
    '726',
    ['the initiative', 'has the initiative', 'l initiative'],
    [
      'The initiative is a designation one player can have, tied to dungeons and the Undercity. It is not the same as the keyword first strike, which French cards call “initiative.” Taking the initiative is described in rule 726. If a question only says “initiative,” it may mean either rule.',
      'L’initiative, dans la règle 726, est une désignation qu’un joueur peut avoir, liée aux donjons et à l’Undercity. Ce n’est pas le mot-clé « initiative » des cartes françaises, qui correspond à first strike en anglais. Prendre l’initiative est décrit à la règle 726. Une question qui dit seulement « initiative » peut viser l’une ou l’autre règle.',
    ],
    [
      'A card tells you to take the initiative. You become the player who has the initiative and follow rule 726. That does not give a creature first strike.',
      'Une carte vous dit de prendre l’initiative. Vous devenez le joueur qui a l’initiative et vous suivez la règle 726. Cela ne donne pas l’initiative (first strike) à une créature.',
    ],
    ['first-strike'],
  ),
];

export const POPULAR_RULE_IDS = [
  'flying',
  'trample',
  'double-strike',
  'hexproof',
  'deathtouch',
] as const;

export const CURATED_BY_ID = new Map(
  CURATED_RULES.map((entry) => [entry.id, entry]),
);
